### ISSUE TITLE
【功能建议】

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [flik1337/huyaEnhance#1]
大佬是否可以添加一个屏蔽虎牙强制下载客户端的代码？

最近虎牙的网页版已经不能再长时间使用画中画模式观看直播了。
时长只要一长就会自动停止画中画模式的播放并弹出虎牙客户端下载链接。

求助大佬添加有关此功能的代码，万分感谢🙏🙏🙏

**Comment by flik1337** [comment]
您好，感谢支持！
画中画功能可以使用一些插件来实现。
推荐chrome官方的Picture-in-Picture，或者SeparateWindow。
https://chrome.google.com/webstore/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg/related?hl=zh-CN
